crms/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from crms.views import continent, country, telcode

app_name = 'crms'
urlpatterns = [
    path('continent/list/', continent.continent_list, name='continent_list'),
    path('continent/add/', continent.continent_add, name='continent_add'),
    path('continent/edit/<int:pk>/', continent.continent_edit, name='continent_edit'),
    path('continent/del/<int:pk>/', continent.continent_del, name='continent_del'),

    path('country/list/', country.country_list, name='country_list'),
    path('country/add/', country.country_add, name='country_add'),
    path('country/edit/<int:pk>/', country.country_edit, name='country_edit'),
    path('country/del/<int:pk>/', country.country_del, name='country_del'),

    path('telcode/list/', telcode.telcode_list, name='telcode_list'),
    path('telcode/add/', telcode.telcode_add, name='telcode_add'),
    path('telcode/edit/<int:pk>/', telcode.telcode_edit, name='telcode_edit'),
    path('telcode/del/<int:pk>/', telcode.telcode_del, name='telcode_del'),

]

day09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include('app01.urls', namespace='app01')),
    path('crms/', include('crms.urls', namespace='crms')),
    path('persons/', include('persons.urls', namespace='persons')),
    path('products/', include('products.urls', namespace='products')),
]

persons/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from persons import views

app_name = 'persons'
urlpatterns = [
    path('', views.person_list, name='person_list'),
    path('add/', views.person_add, name='person_add'),
    path('edit/<int:pk>/', views.person_edit, name='person_edit'),
    path('del/<int:pk>/', views.person_del, name='person_del'),


]

persons/models.py
from django.db import models

from django_countries.fields import CountryField

# Create your models here.

class Person(models.Model):
	name = models.CharField(verbose_name='姓名', max_length=30)
	country = CountryField(verbose_name='国家', null=True, blank=True)

	def __str__(self):
		return self.name

persons/forms/person.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-23 0023 12:34 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : person.py 
# @Software: PyCharm
from django import forms
from persons import models

from tools.bootstrap import BootstrapForm

class PersonForm(BootstrapForm, forms.ModelForm):

	class Meta:
		model = models.Person
		fields = '__all__'

persons/views.py
from django.shortcuts import render,redirect

from persons import models
from persons.forms.person import PersonForm

# Create your views here.

def person_list(request):
	obj = models.Person.objects.all()
	return render(request, 'persons/persons_list.html',{'person_obj':obj})


def person_add(request):
	if request.method == 'POST':
		form = PersonForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('persons:person_list')
		else:
			return render(request,'persons/change.html',{'form':form})
	form = PersonForm()
	return render(request,'persons/change.html',{'form':form})


def person_edit(request, pk):
	pass

def person_del(request, pk):
	pass

templates/persons/change.html
{% extends 'base.html' %}

{% block title %} 操作管理 - CRMS {% endblock title %}

{% block content %}

	<div class="page-tb">
		<form class="form-horizontal" method="post" novalidate>
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
				<div class="col-sm-8">
					{{ field }}
					<span class="error-message">{{ field.errors.0 }}</span>
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">确 认</button>
				</div>
			</div>
		</form>

	</div> <!--/.表格-->

{% endblock content %}

templates/persons/persons_list.html
{% extends 'base.html' %}

{% block title %} 个人列表 - CRMS {% endblock title %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="#">首页</a></li>
		<li><a href="{% url 'crms:telcode_list' %}">个人</a></li>
	</ol>
	<div class="page-header">
		<h2>个人列表</h2>
	</div>

	<div class="page-btn">
		<div class="col-md-10">

		</div>
		<div class="col-md-2">
			<a type="button" class="btn btn-success" href="{% url 'persons:person_add' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增记录</a>
		</div>
	</div> <!--/.表头内容-->
	<div class="page-tb">
		<table class="table table-hover table-bordered">
			<thead>
			<tr>
				<th>#</th>
				<th>姓名</th>
				<th>Code</th>
				<th>alpha3</th>
				<th>numeric</th>
				<th>国家名称</th>
				<th>国家国旗</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{% for item in person_obj %}
				<tr>
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.name }}</td>
					<td>{{ item.country.code }}</td>
					<td>{{ item.country.alpha3 }}</td>
					<td>{{ item.country.numeric }}</td>
					<td>{{ item.country.name }}</td>
					<td><img src="{{ item.country.flag }}"></td>
					<td>
						<a href="{% url 'persons:person_edit' item.id %}"><i class="fa fa-file-text" aria-hidden="true"></i></a>
						<a href="{% url 'persons:person_del' item.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td colspan="4">无相关记录！</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div> <!--/.表格-->

{% endblock content %}