crms/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from crms.views import continent, country, telcode

app_name = 'crms'
urlpatterns = [
    path('continent/list/', continent.continent_list, name='continent_list'),
    path('continent/add/', continent.continent_add, name='continent_add'),
    path('continent/edit/<int:pk>/', continent.continent_edit, name='continent_edit'),
    path('continent/del/<int:pk>/', continent.continent_del, name='continent_del'),

    path('country/list/', country.country_list, name='country_list'),
    path('country/add/', country.country_add, name='country_add'),
    path('country/edit/<int:pk>/', country.country_edit, name='country_edit'),
    path('country/del/<int:pk>/', country.country_del, name='country_del'),

    path('telcode/list/', telcode.telcode_list, name='telcode_list'),
    path('telcode/add/', telcode.telcode_add, name='telcode_add'),
    path('telcode/edit/<int:pk>/', telcode.telcode_edit, name='telcode_edit'),
    path('telcode/del/<int:pk>/', telcode.telcode_del, name='telcode_del'),

]

day09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include('app01.urls', namespace='app01')),
    path('crms/', include('crms.urls', namespace='crms')),
    path('persons/', include('persons.urls', namespace='persons')),
    path('products/', include('products.urls', namespace='products')),
]

products/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
     path('category/', views.category_list, name='category_list'),
     path('category/add/', views.category_add, name='category_add'),
     path('category/edit/<int:pk>/', views.category_edit, name='category_edit'),
     path('category/del/<int:pk>/', views.category_del, name='category_del'),


]

products/models.py
from django.db import models

from tools.validators import validate_file_size


# Create your models here.

class Category(models.Model):
	"""产品分类"""
	category = models.CharField(verbose_name='产品分类', max_length=32)
	parent_category = models.ForeignKey(verbose_name='父类', to='Category', on_delete=models.CASCADE, null=True, blank=True, related_name='Cate_P', default='无')
	cate_desc = models.CharField(verbose_name='产品分类说明', max_length=200, null=True, blank=True, default='无')

	def __str__(self):
		return self.category

class Products(models.Model):
	"""产品表"""
	name = models.CharField(verbose_name='产品名称', max_length=200)
	category = models.ForeignKey(verbose_name='产品类别', to=Category, on_delete=models.CASCADE)
	product_photo = models.ImageField(verbose_name='产品图片', upload_to='upload/products/', blank=True, validators=[validate_file_size,])

	def __str__(self):
		return self.name
class ProductRelative(models.Model):
	"""产品相关表"""
	pass

products/forms.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-23 0023 15:45 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : forms.py 
# @Software: PyCharm

from django import forms
from django.core.exceptions import ValidationError
from products import models
from tools.bootstrap import BootstrapForm


class CategoryForm(BootstrapForm, forms.ModelForm):
	class Meta:
		model = models.Category
		fields = '__all__'

	def clean_category(self):
		category = self.cleaned_data['category']
		# 在models查找不重复
		exist = models.Category.objects.filter(category=category).exclude(id=self.instance.pk).exists()
		if exist:
			raise ValidationError('产品分类已存在!')
		else:
			return category


class ProductForm(BootstrapForm, forms.ModelForm):
	class Meta:
		model = models.Products
		fields = '__all__'

products/views.py
from django.shortcuts import render, redirect, HttpResponse, reverse
from products import models
from products.forms import CategoryForm

# Create your views here.


def category_list(request):
	cate_obj = models.Category.objects.all()
	return render(request, 'products/category.html',{'cate_obj':cate_obj})

def category_add(request):
	if request.method == 'POST':
		form = CategoryForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('products:category_list')
		else:
			return render(request, 'products/change.html', {'form': form})
	form = CategoryForm()
	return render(request, 'products/change.html', {'form': form})

def category_edit(request, pk):
	continent_obj = models.Category.objects.filter(id=pk).first()
	if not continent_obj:
		return HttpResponse('数据不存在')
	if request.method == 'GET':
		form = CategoryForm(instance=continent_obj)
		return render(request, 'products/change.html', {'form': form})
	form = CategoryForm(instance=continent_obj, data=request.POST)
	if form.is_valid():
		form.save()
		return redirect('products:category_list')
	return render(request, 'products/change.html', {'form': form})

def category_del(request, pk):
	origin_url = reverse('products:category_list')
	if request.method == 'GET':
		return render(request, 'alarm.html', {'cancel': origin_url})
	models.Category.objects.filter(id=pk).delete()
	return redirect('products:category_list')

templates/products/category.html
{% extends 'base.html' %}

{% block title %} 产品分类 - CRMS {% endblock title %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="#">首页</a></li>
		<li><a href="{% url 'products:category_list' %}">分类</a></li>
	</ol>
	<div class="page-header">
		<h2>产品分类列表</h2>
	</div>

	<div class="page-btn">
		<div class="col-md-10">

		</div>
		<div class="col-md-2">
			<a type="button" class="btn btn-success" href="{% url 'products:category_add' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增记录</a>
		</div>
	</div> <!--/.表头内容-->
	<div class="page-tb">
		<table class="table table-hover table-bordered">
			<thead>
			<tr>
				<th>#</th>
				<th>产品分类</th>
				<th>父类</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{% for item in cate_obj %}
				<tr>
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.category }}</td>
					{% if item.parent_category %}
						<td>{{ item.parent_category }}</td>
					{% else %}
						<td> </td>
					{% endif %}
					<td>
						<a href="{% url 'products:category_edit' item.id %}"><i class="fa fa-file-text" aria-hidden="true"></i></a>
						<a href="{% url 'products:category_del' item.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td colspan="4">无相关记录！</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div> <!--/.表格-->

{% endblock content %}

templates/products/change.html
{% extends 'base.html' %}

{% block title %} 操作管理 - CRMS {% endblock title %}

{% block content %}

	<div class="page-tb">
		<form class="form-horizontal" method="post" novalidate>
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
				<div class="col-sm-8">
					{{ field }}
					<span class="error-message">{{ field.errors.0 }}</span>
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">确 认</button>
				</div>
			</div>
		</form>

	</div> <!--/.表格-->

{% endblock content %}