crms/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from crms.views import continent, country, telcode

app_name = 'crms'
urlpatterns = [
    path('continent/list/', continent.continent_list, name='continent_list'),
    path('continent/add/', continent.continent_add, name='continent_add'),
    path('continent/edit/<int:pk>/', continent.continent_edit, name='continent_edit'),
    path('continent/del/<int:pk>/', continent.continent_del, name='continent_del'),

    path('country/list/', country.country_list, name='country_list'),
    path('country/add/', country.country_add, name='country_add'),
    path('country/edit/<int:pk>/', country.country_edit, name='country_edit'),
    path('country/del/<int:pk>/', country.country_del, name='country_del'),

    path('telcode/list/', telcode.telcode_list, name='telcode_list'),
    path('telcode/add/', telcode.telcode_add, name='telcode_add'),
    path('telcode/edit/<int:pk>/', telcode.telcode_edit, name='telcode_edit'),
    path('telcode/del/<int:pk>/', telcode.telcode_del, name='telcode_del'),

]

day09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include('app01.urls', namespace='app01')),
    path('crms/', include('crms.urls', namespace='crms')),
    path('persons/', include('persons.urls', namespace='persons')),
    path('products/', include('products.urls', namespace='products')),
]

crms/models.py
from django.db import models


# Create your models here.


class Continent(models.Model):
	"""洲别"""
	name = models.CharField(verbose_name='洲别名称', max_length=20)
	remark = models.CharField(verbose_name='备注', max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name


class Country(models.Model):
	"""国家地区"""
	code = models.CharField(verbose_name='国家代码', max_length=5, unique=True)
	cn_abbr = models.CharField(verbose_name='国家中文简称', max_length=50)
	en_abbr = models.CharField(verbose_name='国家英文简称', max_length=100)
	cn_name = models.CharField(verbose_name='国家中文名称', max_length=200)
	en_name = models.CharField(verbose_name='国家英文名称', max_length=200)
	domain = models.CharField(verbose_name='域名', max_length=5, unique=True)
	continent = models.ForeignKey(verbose_name='所属洲别', to=Continent, on_delete=models.CASCADE)
	remark = models.CharField(verbose_name='备注', max_length=200, null=True, blank=True)

	def __str__(self):
		return '%s(%s)' % (self.en_abbr, self.cn_abbr)


class TelAreaCode(models.Model):
	"""国际电话区号"""
	code = models.CharField(verbose_name='国际电话区号', max_length=10, unique=True)
	country = models.ForeignKey(verbose_name='所属国家', to=Country, on_delete=models.CASCADE)

	def __str__(self):
		return self.code

crms/forms/bootstrap.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 09:27 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : bootstrap.py 
# @Software: PyCharm

class BootstrapForm(object):
    bootstrap_class_exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name in self.bootstrap_class_exclude:
                continue
            old_class = field.widget.attrs.get('class', "")
            field.widget.attrs['class'] = '{} form-control'.format(old_class)
            field.widget.attrs['placeholder'] = '请输入%s' % (field.label,)

crms/forms/continent.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 09:28 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django import forms
from django.core.exceptions import ValidationError
from crms.forms.bootstrap import BootstrapForm
from crms import models


class ContinentForm(BootstrapForm, forms.ModelForm):
	"""洲别ModelForm"""

	class Meta:
		model = models.Continent
		fields = '__all__'
		error_messages = {
			'name': {'required': '洲别名称不能为空！'}
		}

	def clean_name(self):
		name = self.cleaned_data['name']
		# 在models查找不重复
		exist = models.Continent.objects.filter(name=name).exclude(id=self.instance.pk).exists()
		if exist:
			raise ValidationError('洲别名称已存在')
		else:
			return name

crms/forms/country.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 09:28 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django import forms
from django.core.exceptions import ValidationError
from crms.forms.bootstrap import BootstrapForm
from crms import models


class CountryForm(BootstrapForm, forms.ModelForm):
	"""洲别ModelForm"""

	class Meta:
		model = models.Country
		fields = '__all__'

	def clean_code(self):
		code = self.cleaned_data['code']
		# 在models查找不重复
		exist = models.Continent.objects.filter(name=code).exclude(id=self.instance.pk).exists()
		if exist:
			raise ValidationError('国家代码已存在!')
		else:
			return code

crms/forms/telcode.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 09:28 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django import forms
from django.core.exceptions import ValidationError
from crms.forms.bootstrap import BootstrapForm
from crms import models


class TelCodeForm(BootstrapForm, forms.ModelForm):
	"""国际电话区号ModelForm"""

	class Meta:
		model = models.TelAreaCode
		fields = '__all__'


	def clean_code(self):
		code = self.cleaned_data['code']
		# 在models查找不重复
		exist = models.TelAreaCode.objects.filter(code=code).exclude(id=self.instance.pk).exists()
		if exist:
			raise ValidationError('国际电话区号已存在')
		else:
			return code

crms/views/continent.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 10:50 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django.shortcuts import render, redirect, HttpResponse, reverse
from crms.forms.continent import ContinentForm
from crms import models


# Create your views here.
def continent_list(request):
	"""洲别列表"""
	continent_obj = models.Continent.objects.all()
	return render(request, 'crms/continent_list.html', {'continent_obj': continent_obj})


def continent_add(request):
	"""洲别新增"""
	if request.method == 'POST':
		form = ContinentForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('crms:continent_list')
		else:
			return render(request, 'crms/change.html', {'form': form})
	form = ContinentForm()
	return render(request, 'crms/change.html', {'form': form})


def continent_edit(request, pk):
	"""洲别修改"""
	continent_obj = models.Continent.objects.filter(id=pk).first()
	if not continent_obj:
		return HttpResponse('数据不存在')
	if request.method == 'GET':
		form = ContinentForm(instance=continent_obj)
		return render(request, 'crms/change.html', {'form': form})
	form = ContinentForm(instance=continent_obj, data=request.POST)
	if form.is_valid():
		form.save()
		return redirect('crms:continent_list')
	return render(request, 'crms/change.html', {'form': form})

def continent_del(request, pk):
	"""洲别删除"""
	origin_url = reverse('crms:continent_list')
	if request.method == 'GET':
		return render(request, 'alarm.html', {'cancel': origin_url})
	models.Continent.objects.filter(id = pk).delete()
	return redirect('crms:continent_list')

crms/views/country.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 10:50 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django.shortcuts import render, redirect, HttpResponse, reverse
from crms.forms.country import CountryForm
from crms import models


# Create your views here.
def country_list(request):
	"""国家列表"""
	country_obj = models.Country.objects.all()
	return render(request, 'crms/country_list.html', {'country_obj': country_obj})


def country_add(request):
	"""国家新增"""
	if request.method == 'POST':
		form = CountryForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('crms:country_list')
		else:
			return render(request, 'crms/change.html', {'form': form})
	form = CountryForm()
	return render(request, 'crms/change.html', {'form': form})


def country_edit(request, pk):
	"""洲别修改"""
	country_obj = models.Country.objects.filter(id=pk).first()
	if not country_obj:
		return HttpResponse('数据不存在')
	if request.method == 'GET':
		form = CountryForm(instance=country_obj)
		return render(request, 'crms/change.html', {'form': form})
	form = CountryForm(instance=country_obj, data=request.POST)
	if form.is_valid():
		form.save()
		return redirect('crms:country_list')
	return render(request, 'crms/change.html', {'form': form})

def country_del(request, pk):
	"""洲别删除"""
	origin_url = reverse('crms:country_list')
	if request.method == 'GET':
		return render(request, 'alarm.html', {'cancel': origin_url})
	models.CountryForm.objects.filter(id = pk).delete()
	return redirect('crms:country_list')

crms/views/telcode.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-22 0022 10:50 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : continent.py 
# @Software: PyCharm

from django.shortcuts import render, redirect, HttpResponse, reverse
from crms.forms.telcode import TelCodeForm
from crms import models


# Create your views here.
def telcode_list(request):
	"""国际电话区号列表"""
	telcode_obj = models.TelAreaCode.objects.all()
	return render(request, 'crms/telcode_list.html', {'telcode_obj': telcode_obj})


def telcode_add(request):
	"""国际电话区号新增"""
	if request.method == 'POST':
		form = TelCodeForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('crms:telcode_list')
		else:
			return render(request, 'crms/change.html', {'form': form})
	form = TelCodeForm()
	return render(request, 'crms/change.html', {'form': form})


def telcode_edit(request, pk):
	"""国际电话区号修改"""
	continent_obj = models.TelAreaCode.objects.filter(id=pk).first()
	if not continent_obj:
		return HttpResponse('数据不存在')
	if request.method == 'GET':
		form = TelCodeForm(instance=continent_obj)
		return render(request, 'crms/change.html', {'form': form})
	form = TelCodeForm(instance=continent_obj, data=request.POST)
	if form.is_valid():
		form.save()
		return redirect('crms:telcode_list')
	return render(request, 'crms/change.html', {'form': form})

def telcode_del(request, pk):
	"""国际电话区号删除"""
	origin_url = reverse('crms:telcode_list')
	if request.method == 'GET':
		return render(request, 'alarm.html', {'cancel': origin_url})
	models.TelAreaCode.objects.filter(id = pk).delete()
	return redirect('crms:telcode_list')

templates/crms/change.html
{% extends 'base.html' %}

{% block title %} 操作管理 - CRMS {% endblock title %}

{% block content %}

	<div class="page-tb">
		<form class="form-horizontal" method="post" novalidate>
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
				<div class="col-sm-8">
					{{ field }}
					<span class="error-message">{{ field.errors.0 }}</span>
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">确 认</button>
				</div>
			</div>
		</form>

	</div> <!--/.表格-->

{% endblock content %}

templates/crms/continent_list.html
{% extends 'base.html' %}

{% block title %} 洲别列表 - CRMS {% endblock title %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="#">首页</a></li>
		<li><a href="{% url 'crms:continent_list' %}">洲别</a></li>
		<li class="active">列表</li>
	</ol>
	<div class="page-header">
		<h2>洲别列表</h2>
	</div>

	<div class="page-btn">
		<div class="col-md-10">

		</div>
		<div class="col-md-2">
			<a type="button" class="btn btn-success" href="{% url 'crms:continent_add' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增记录</a>
		</div>
	</div> <!--/.表头内容-->
	<div class="page-tb">
		<table class="table table-hover table-bordered">
			<thead>
			<tr>
				<th>#</th>
				<th>洲别名称</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{% for item in continent_obj %}
				<tr>
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.name }}</td>
					<td>{{ item.remark }}</td>
					<td>
						<a href="{% url 'crms:continent_edit' item.id %}"><i class="fa fa-file-text" aria-hidden="true"></i> </a>
						 <a href="{% url 'crms:continent_del' item.id %}"> <i class="fa fa-trash-o" aria-hidden="true"></i> </a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td colspan="4">无相关记录！</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div> <!--/.表格-->

{% endblock content %}

templates/crms/country_list.html
{% extends 'base.html' %}

{% block title %} 国家列表 - CRMS {% endblock title %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="#">首页</a></li>
		<li><a href="{% url 'crms:country_list' %}">国家</a></li>
		<li class="active">列表</li>
	</ol>
	<div class="page-header">
		<h2>国家列表</h2>
	</div>

	<div class="page-btn">
		<div class="col-md-10">

		</div>
		<div class="col-md-2">
			<a type="button" class="btn btn-success" href="{% url 'crms:country_add' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增记录</a>
		</div>
	</div> <!--/.表头内容-->
	<div class="page-tb">
		<table class="table table-hover table-bordered">
			<thead>
			<tr>
				<th>#</th>
				<th>国家编号</th>
				<th>国家中文简称</th>
				<th>国家英文简称</th>
				<th>国家中文名称</th>
				<th>国家英文名称</th>
				<th>域名</th>
				<th>所属洲别</th>
				<th>关联</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{% for item in country_obj %}
				<tr>
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.code }}</td>
					<td>{{ item.cn_abbr }}</td>
					<td>{{ item.en_abbr }}</td>
					<td>{{ item.cn_name }}</td>
					<td>{{ item.en_name }}</td>
					<td>{{ item.domain }}</td>
					<td>{{ item.continent }}</td>
					<td>
						<a href="{% url 'crms:telcode_list' %}">区号</a>
						<a href="#">港口</a>
						<a href="#">机场</a>
					</td>
					<td>
						<a href="{% url 'crms:country_edit' item.id %}"><i class="fa fa-file-text" aria-hidden="true"></i></a>
						<a href="{% url 'crms:country_del' item.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>

					</td>
				</tr>
			{% empty %}
				<tr>
					<td colspan="10">无相关记录！</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div> <!--/.表格-->

{% endblock content %}

templates/crms/telcode_list.html
{% extends 'base.html' %}

{% block title %} 国际区号列表 - CRMS {% endblock title %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="#">首页</a></li>
		<li><a href="{% url 'crms:telcode_list' %}">国际区号</a></li>
	</ol>
	<div class="page-header">
		<h2>国际区号列表</h2>
	</div>

	<div class="page-btn">
		<div class="col-md-10">

		</div>
		<div class="col-md-2">
			<a type="button" class="btn btn-success" href="{% url 'crms:telcode_add' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增记录</a>
		</div>
	</div> <!--/.表头内容-->
	<div class="page-tb">
		<table class="table table-hover table-bordered">
			<thead>
			<tr>
				<th>#</th>
				<th>国际电话区号</th>
				<th>所属国家</th>
				<th>操作</th>
			</tr>
			</thead>
			<tbody>
			{% for item in telcode_obj %}
				<tr>
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.code }}</td>
					<td>{{ item.country }}</td>
					<td>
						<a href="{% url 'crms:telcode_edit' item.id %}"><i class="fa fa-file-text" aria-hidden="true"></i></a>
						<a href="{% url 'crms:telcode_del' item.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td colspan="4">无相关记录！</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div> <!--/.表格-->

{% endblock content %}