crms/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from crms.views import continent, country, telcode

app_name = 'crms'
urlpatterns = [
    path('continent/list/', continent.continent_list, name='continent_list'),
    path('continent/add/', continent.continent_add, name='continent_add'),
    path('continent/edit/<int:pk>/', continent.continent_edit, name='continent_edit'),
    path('continent/del/<int:pk>/', continent.continent_del, name='continent_del'),

    path('country/list/', country.country_list, name='country_list'),
    path('country/add/', country.country_add, name='country_add'),
    path('country/edit/<int:pk>/', country.country_edit, name='country_edit'),
    path('country/del/<int:pk>/', country.country_del, name='country_del'),

    path('telcode/list/', telcode.telcode_list, name='telcode_list'),
    path('telcode/add/', telcode.telcode_add, name='telcode_add'),
    path('telcode/edit/<int:pk>/', telcode.telcode_edit, name='telcode_edit'),
    path('telcode/del/<int:pk>/', telcode.telcode_del, name='telcode_del'),

]

day09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include('app01.urls', namespace='app01')),
    path('crms/', include('crms.urls', namespace='crms')),
    path('persons/', include('persons.urls', namespace='persons')),
    path('products/', include('products.urls', namespace='products')),
]

products/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time : 2022-9-17 0017 08:54 
# @Author: Orsonz
# @Email: orsonz@163.com
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
     path('category/', views.category_list, name='category_list'),
     path('category/add/', views.category_add, name='category_add'),
     path('category/edit/<int:pk>/', views.category_edit, name='category_edit'),
     path('category/del/<int:pk>/', views.category_del, name='category_del'),


]

templates/alarm.html
{% extends 'base.html' %}

{% block title %} 警告信息 {% endblock title %}

{% block css %} {% endblock css %}

{% block content %}
<form method="post">
{% csrf_token %}
	<div class="alert alert-danger" role="alert">
		<strong>慎重!</strong> 你确定删除吗？
	</div>

	<div>
		<a type="button" class="btn btn-danger" href="{{ cancel }}">取 消</a>
		<button type="submit" class="btn btn-primary">确 认</button>
	</div>
</form>

{% endblock content %}

{% block js %} {% endblock js %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
	<title>{% block title %} 后台 {% endblock title %} </title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datetimepicker.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	{% block css %} {% endblock css %}

</head>
<body>

{% include 'nav.html' %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			{% include 'sidebar.html' %}
		</div> <!--/.左侧菜单-->

		<div class="col-md-10 page-content">
			{% block content %} {% endblock content %}
		</div> <!--/.右侧内容-->
	</div>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'js/bs_datetimepicker.js' %}"></script>



{% block js %}

{% endblock js %}

</body>
</html>

templates/c.html
<ol class="breadcrumb">
	<li><a href="#">首页</a></li>
	<li><a href="#">工作台</a></li>
	<li class="active">Data</li>
</ol>
<div class="page-header">
	<h2>国家信息</h2>
</div>

<div class="page-btn">
	<div class="col-md-9">
		<form class="form-inline">
			<div class="form-group">
				<label for="exampleInputName2">Name</label>
				<input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
			</div>
			<button type="submit" class="btn btn-default">搜索</button>
		</form>
	</div>
	<div class="col-md-3">
		<button type="button" class="btn btn-primary">新增记录</button>
	</div>
</div> <!--/.表头内容-->
<div class="page-tb">
	<table class="table table-hover table-bordered">
		<thead>
		<tr>
			<th>#</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Username</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<th scope="row">1</th>
			<td>Mark</td>
			<td>Otto</td>
			<td>@mdo</td>
		</tr>
		<tr>
			<th scope="row">2</th>
			<td>Jacob</td>
			<td>Thornton</td>
			<td>@fat</td>
		</tr>
		<tr>
			<th scope="row">3</th>
			<td>Larry</td>
			<td>the Bird</td>
			<td>@twitter</td>
		</tr>
		</tbody>
	</table>
</div> <!--/.表格-->

templates/nav.html
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Brand</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
					   aria-expanded="false">投票 <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">列表</a></li>
						<li><a href="#">详情</a></li>
						<li><a href="#">投票</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
			</ul>
			<form class="navbar-form navbar-left">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
					   aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

templates/sidebar.html
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="headingOne">
			<h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
				   aria-expanded="true" aria-controls="collapseOne">
					基础资料
				</a>
			</h4>
		</div>
		<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
			 aria-labelledby="headingOne">
			<div class="panel-body">
				<ul class="list-group">
					<li class="list-group-item"><a href="{% url 'crms:continent_list' %}">洲别</a></li>
					<li class="list-group-item"><a href="{% url 'crms:country_list' %}">国家</a></li>
					<li class="list-group-item">航线</li>
					<li class="list-group-item">港口</li>
					<li class="list-group-item">机场</li>
					<li class="list-group-item"><a href="{% url 'crms:telcode_list' %}">国际区号</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="headingTwo">
			<h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
				   href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
					产品资料库
				</a>
			</h4>
		</div>
		<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
			<div class="panel-body">
				<ul class="list-group">
					<li class="list-group-item"><a href="#">产品资料</a></li>
					<li class="list-group-item"><a href="{% url 'products:category_list' %}">产品分类</a></li>
					<li class="list-group-item"><a href="#">产品报价</a></li>
					<li class="list-group-item"><a href="#">产品图库</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="headingThree">
			<h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
				   href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
					Collapsible Group Item #3
				</a>
			</h4>
		</div>
		<div id="collapseThree" class="panel-collapse collapse" role="tabpanel"
			 aria-labelledby="headingThree">
			<div class="panel-body">
				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad
				squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
				nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
				single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft
				beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice
				lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you
				probably haven't heard of them accusamus labore sustainable VHS.
			</div>
		</div>
	</div>
</div>